trigger:
- main

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

stages:
- stage: Build
  jobs: 
  - job: Job1
    steps:
    - bash: |
        echo $(buildName)
        echo $(date +%Y)
  - job: Job2
    steps:
    - bash: |
        echo $(date +%Y)
