parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

trigger:
- main

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

stages:
- stage: Build
  jobs: 
  - job: Job1
    steps:
    - script: java --version
    displayName: Print JAVA version