trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac


parameters:
  - name: pGroupVariablesName
    displayName: "Name of the variable group"
    type: string
    default: RPVariableGroup1
    values:
      - RPVariableGroup1
      - RPVariableGroup2
      - RPVariableGroup3

  - name: pazureServiceConnection
    displayName: "azure Service Connection"
    type: string
    default: service-connection-1
    values:
      - service-connection-1
      - service-connection-2
      - service-connection-3
  - name: pnumberOfInstances
    displayName: "Number of Instances"
    type: string
    default: '2'
    values:
      - '2'
      - '3'
      - '4'
  - name: pEnvironment
    displayName: "Environment"
    type: string
    default: DEV
    values:
      - DEV
      - TEST
      - ACC
      - PROD

variables: 
    - group: ${{ parameters.pGroupVariablesName}}

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs: 
  - job: BuildJob1
    displayName: 'Component 1 - Build job'
    steps:
      - script: |
          echo 'Build stage --> Inside Component 1 - Build Job'  
  - job: BuildJob2
    displayName: 'Component 2 - Build job'
    steps:
      - script: |
          echo 'Build stage --> Inside Component 2 - Build Job'  
          
- stage: Test
  displayName: 'Test Stage'
  jobs: 
  - job: StageJob1
    displayName: 'Component 1 - Test job'
    steps:
      - script: |
          echo 'Test stage --> Inside Component 1 - Test Job'  
  - job: StageJob1
    displayName: 'Component 2 - Test job'
    steps:
      - script: |
          echo 'Test stage --> Inside Component 2 - Test Job'  

- stage: CodeCoverage
  displayName: 'Code Coverage Stage'
  jobs: 
  - job: CCJob1
    displayName: 'Component 1 - Code Coverage job'
    steps:
      - script: |
          echo 'Code Coverage stage --> Inside Component 1 - CC Job'  
  - job: StageJob1
    displayName: 'Component 2 - Test job'
    steps:
      - script: |
          echo 'Code Coverage stage --> Inside Component 2 - CC Job'
