trigger: none

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac


parameters:
  - name: pGroupVariablesName
    displayName: "Name of the variable group"
    type: string
    default: RPVariableGroup1
    values:
      - RPVariableGroup1
      - RPVariableGroup2
      - RPVariableGroup3

  - name: pazureServiceConnection
    displayName: "azure Service Connection"
    type: string
    default: service-connection-1
    values:
      - service-connection-1
      - service-connection-2
      - service-connection-3
  - name: pnumberOfInstances
    displayName: "Number of Instances"
    type: string
    default: '2'
    values:
      - '2'
      - '3'
      - '4'
  - name: pEnvironment
    displayName: "Environment"
    type: string
    default: DEV
    values:
      - DEV
      - TEST
      - ACC
      - PROD

variables: 
    - group: ${{ parameters.pGroupVariablesName}}

stages:
- stage: BuildStage
  displayName: 'Build Stage'
  jobs: 
  - job: BuildJob1
    displayName: 'Component 1 - Build job'
    steps:
      - script: |
          echo 'Build stage --> Inside Component 1 - Build Job'  
  - job: BuildJob2
    displayName: 'Component 2 - Build job'
    steps:
      - script: |
          echo 'Build stage --> Inside Component 2 - Build Job'  
          
- stage: TestStage
  displayName: 'Test Stage'
  jobs: 
  - job: TestJob1
    displayName: 'Component 1 - Test job'
    steps:
      - script: |
          echo 'Test stage --> Inside Component 1 - Test Job'  
  - job: TestJob2
    displayName: 'Component 2 - Test job'
    steps:
      - script: |
          echo 'Test stage --> Inside Component 2 - Test Job'  

- stage: CodeCoverage
  displayName: 'Code Coverage Stage'
  jobs: 
  - job: CCJob1
    displayName: 'Component 1 - Code Coverage job'
    steps:
      - script: |
          echo 'Code Coverage stage --> Inside Component 1 - CC Job'  
  - job: CCJob2
    displayName: 'Component 2 - Test job'
    steps:
      - script: |
          echo 'Code Coverage stage --> Inside Component 2 - CC Job'

- stage: StaticAnalysis
  displayName: 'Static Analysis Stage'
  jobs: 
  - job: CCJob1
    displayName: 'Component 1 - Static Analysis job'
    steps:
      - script: |
          echo 'Static Analysis stage --> Inside Component 1 - SA Job'  
  - job: CCJob2
    displayName: 'Component 2 - Static Analysis job'
    steps:
      - script: |
          echo 'Static Analysis stage --> Inside Component 2 - SA Job'

- stage: CompositionAnalysis
  displayName: 'Composition Analysis Stage'
  jobs: 
  - job: CAJob1
    displayName: 'Component 1 - Composition Analysis job'
    steps:
      - script: |
          echo 'Composition Analysis stage --> Inside Component 1 - CA Job'  
  - job: CAJob2
    displayName: 'Component 2 - Composition Analysis job'
    steps:
      - script: |
          echo 'Composition Analysis stage --> Inside Component 2 - CA Job'

- stage: UploadArtifact
  displayName: 'Upload Artifact Stage'
  jobs: 
  - job: UAJob1
    displayName: 'Component 1 - Upload Artifact job'
    steps:
      - script: |
          echo 'Upload Artifact stage --> Inside Component 1 - UA Job'  
  - job: UAJob2
    displayName: 'Component 2 - Upload Artifact job'
    steps:
      - script: |
          echo 'Upload Artifact stage --> Inside Component 2 - UA Job'