trigger: none

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

variables:
- group: varPool
- name: one
  value: initialValue 

pool:
  name: RPLocalPool
  demands:
   - agent.name -equals RPLocalMac

stages:
- stage: Build
  jobs: 
  - job: "PrintVersion"
    steps:
    - script: java --version
    displayName: Print JAVA version

- stage: Test
  jobs: 
  - job: "PrintVariables"
    steps:
    - script: |
        echo ${{ variables.one }}
        echo 'Printing of local variables completed'
      displayName: Print value of local variables
    - script: |
        echo ${{ parameters.image }}
        echo 'Printing of parameter variables completed'
      displayName: Print value of Parameter variables
    - script: |
        echo ${{ variables.AgentName }}
        echo 'Printing of AgentName variables completed'
      displayName: Print value of Library variables